export enum RoleId {
  SUPER_USER = 1,
  ADMIN = 2,
  MANAGER = 3,
  CUSTOMER_SUPPORT = 4,
  GUEST = 5,
  HOST = 6,
  PROVIDER_SUPER_ADMIN = 7,
  PROVIDER_ADMIN = 8,
  PROVIDER_MANAGER = 9,
  PROVIDER_CUSTOMER_SUPPORT = 10,
}
